# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ca9077bbb780f249d46b9fc06475f2f4fe76041bbbbe1a4d0de3ac1bfccb1fcf3d716c7a842c66337ab63d18210f241475ca9b640a50fa6b701b02460fd69df

test:
  secret_key_base: 80c389701ea506ddb5c4f5b37d29259bde3799736f1a91a607ef47c705e2ac857192af895d7abd818b2433169c33a4126280b743ca48d0e7fa83421abff7fd79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 80c389701ea506ddb5c4f5b37d29259bde3799736f1a91a607ef47c705e2ac857192af895d7abd818b2433169c33a4126280b743ca48d0e7fa83421abff7fd79
